### ISSUE TITLE
Version 1.501 and breaking backwards compatibility

### ISSUE THREAD

**Issue by ISim** [naturalist/Validate--Tiny#6]
Today morning I created a new build of our application and I could't believe my eyes because almost all tests of API failed with reason:

`Can't use an undefined value as an ARRAY reference at /opt/perl/lib/site_perl/5.16.3/Validate/Tiny.pm line 283`

What the hell is going on, I asked? Well, finally I found it...

I think the way how incompatible changes were made is unfortunate. What do I mean? Simple example:

```perl
use strict;
use Validate::Tiny ':all';

my $v = Validate::Tiny->new( { f1 => undef },
    { fields => ['f1'], checks => [ f1 => is_required() ] } );

if ( !$v->success() ) {
    warn $v->error_string( separator => "\n" );
}
```

In the old version the code produces warn "[f1] required". In the new version the code dies. Well, Validate::Tiny 1.501 is not backwards compatible but in this case I would expect:

* `$v->success()` dies with message like *"Calling success() before calling check()....."*
* `$v->error_string()` produces message like *"error_string() method is deprecated...."*

It will help to detect what's happened without looking into code.

Even more the construction in AUTOLOAD https://github.com/naturalist/Validate--Tiny/blob/master/lib/Validate/Tiny.pm#L280

```perl
 elsif ( $sub =~ /(data|error)/ ) {
```

is incorrect. Because 

```perl
$validator->look_data_are_missing()
```

doesn't produce the message `Validate::Tiny::look_data_are_missing ` but dies with

`Can't use an undefined value as a HASH reference at /opt/perl/lib/site_perl/5.16.3/Validate/Tiny.pm line 290`

There should be `elsif ( $sub =~ /^(data|error)$/ ) {` at least. The same with line 277 and ` $sub =~ /(params|rules)/` - again to make clear what happened.

What do you think?

**Comment by naturalist** [comment]
Yet, this version for V::T is not backwards compatible. Please look at the Changes file for more information. The quick fix for your current code is to replace any `new` with `check`. For example:

```perl
my $v = Validate::Tiny->check( { f1 => undef },
    { fields => ['f1'], checks => [ f1 => is_required() ] } );
```
The `new` method is now just a constructor, which allows you to specify a hashref with custom filters. See the POD for more info.
